% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{5}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{float}
\floatplacement{table}{H}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={US Baby Naming Trends \& Cultural Influences},
  pdfauthor={Data Science Report for Toy Design Agency},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{US Baby Naming Trends \& Cultural Influences}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Question 2 --- Stellenbosch University 2026 Data Science
Practical}
\author{Data Science Report for Toy Design Agency}
\date{June 18, 2026}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{Setup}\label{setup}

\subsection{Libraries and Source
Scripts}\label{libraries-and-source-scripts}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{library}\NormalTok{(tidyverse)}
\FunctionTok{library}\NormalTok{(scales)}
\FunctionTok{library}\NormalTok{(glue)}
\FunctionTok{library}\NormalTok{(knitr)}
\FunctionTok{library}\NormalTok{(kableExtra)}

\CommentTok{\# ── Source all helper functions from code/ ───────────────────────────────────}
\FunctionTok{list.files}\NormalTok{(}\StringTok{\textquotesingle{}code/\textquotesingle{}}\NormalTok{, }\AttributeTok{full.names =} \ConstantTok{TRUE}\NormalTok{, }\AttributeTok{recursive =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{    .[}\FunctionTok{grepl}\NormalTok{(}\StringTok{\textquotesingle{}.R$\textquotesingle{}}\NormalTok{, .)] }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{as.list}\NormalTok{() }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{walk}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\FunctionTok{source}\NormalTok{(.))}
\end{Highlighting}
\end{Shaded}

\subsection{Load Data}\label{load-data}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{rds\_paths }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}
    \AttributeTok{Baby\_Names        =} \StringTok{"data/US\_Baby\_names/Baby\_Names\_By\_US\_State.rds"}\NormalTok{,}
    \AttributeTok{Top\_100\_Billboard =} \StringTok{"data/US\_Baby\_names/charts.rds"}\NormalTok{,}
    \AttributeTok{HBO\_titles        =} \StringTok{"data/US\_Baby\_names/HBO\_titles.rds"}\NormalTok{,}
    \AttributeTok{HBO\_credits       =} \StringTok{"data/US\_Baby\_names/HBO\_credits.rds"}
\NormalTok{)}

\NormalTok{datasets }\OtherTok{\textless{}{-}} \FunctionTok{map}\NormalTok{(rds\_paths, load\_rds)}

\NormalTok{Baby\_Names        }\OtherTok{\textless{}{-}}\NormalTok{ datasets}\SpecialCharTok{$}\NormalTok{Baby\_Names}
\NormalTok{Top\_100\_Billboard }\OtherTok{\textless{}{-}}\NormalTok{ datasets}\SpecialCharTok{$}\NormalTok{Top\_100\_Billboard}
\NormalTok{HBO\_titles        }\OtherTok{\textless{}{-}}\NormalTok{ datasets}\SpecialCharTok{$}\NormalTok{HBO\_titles}
\NormalTok{HBO\_credits       }\OtherTok{\textless{}{-}}\NormalTok{ datasets}\SpecialCharTok{$}\NormalTok{HBO\_credits}

\CommentTok{\# National aggregation}
\NormalTok{national }\OtherTok{\textless{}{-}} \FunctionTok{aggregate\_national}\NormalTok{(Baby\_Names)}
\end{Highlighting}
\end{Shaded}

\section{Exploratory Overview}\label{exploratory-overview}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{year\_range }\OtherTok{\textless{}{-}} \FunctionTok{range}\NormalTok{(national}\SpecialCharTok{$}\NormalTok{Year)}
\NormalTok{n\_unique   }\OtherTok{\textless{}{-}} \FunctionTok{n\_distinct}\NormalTok{(national}\SpecialCharTok{$}\NormalTok{Name)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{national }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(Year, Gender) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{Births =} \FunctionTok{sum}\NormalTok{(Total), }\AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Year, }\AttributeTok{y =}\NormalTok{ Births, }\AttributeTok{colour =}\NormalTok{ Gender)) }\SpecialCharTok{+}
    \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{linewidth =} \FloatTok{0.9}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ comma) }\SpecialCharTok{+}
    \FunctionTok{scale\_colour\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"F"} \OtherTok{=} \StringTok{"\#E76F51"}\NormalTok{, }\StringTok{"M"} \OtherTok{=} \StringTok{"\#2A9D8F"}\NormalTok{),}
                        \AttributeTok{labels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Girls"}\NormalTok{, }\StringTok{"Boys"}\NormalTok{)) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Total Recorded Births by Year and Gender"}\NormalTok{,}
         \AttributeTok{subtitle =} \FunctionTok{glue}\NormalTok{(}\StringTok{"\{year\_range[1]\}{-}{-}\{year\_range[2]\} across all US states"}\NormalTok{),}
         \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{y =} \StringTok{"Total Births"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{13}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"top"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Q2_Baby_Name_files/figure-latex/overview-plot-1} \end{center}

\textbf{Key observations:}

\begin{itemize}
\tightlist
\item
  The dataset covers \textbf{30,274} unique names from \textbf{1910} to
  \textbf{2014}.
\item
  Both genders peak in the late 1950s--1960s (baby boom), then decline.
\item
  Girls' names are more diverse --- the same total births spread across
  more unique names.
\end{itemize}

\newpage

\section{Naming Persistence: Spearman Rank
Correlation}\label{naming-persistence-spearman-rank-correlation}

I compute \textbf{Spearman \(\rho\)} between each year's top-25 names
and the rankings 1, 2 and 3 years later.

\begin{quote}
\(\rho \approx 1\) means the same names stayed popular in the same
order; \(\rho \approx 0\) means the rankings shuffled completely.
\end{quote}

\subsection{Time-Series Plot}\label{time-series-plot}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{persistence\_df }\OtherTok{\textless{}{-}} \FunctionTok{build\_persistence\_grid}\NormalTok{(national, }\AttributeTok{lags =} \DecValTok{1}\SpecialCharTok{:}\DecValTok{3}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{persistence\_df }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}
        \AttributeTok{Gender\_label =} \FunctionTok{if\_else}\NormalTok{(Gender }\SpecialCharTok{==} \StringTok{"F"}\NormalTok{, }\StringTok{"Girls"}\NormalTok{, }\StringTok{"Boys"}\NormalTok{),}
        \AttributeTok{Lag\_label    =} \FunctionTok{glue}\NormalTok{(}\StringTok{"\{Lag\}{-}Year Lag"}\NormalTok{)}
\NormalTok{    ) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Year, }\AttributeTok{y =}\NormalTok{ Correlation, }\AttributeTok{colour =}\NormalTok{ Lag\_label)) }\SpecialCharTok{+}
    \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.4}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{0.5}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{se =} \ConstantTok{FALSE}\NormalTok{, }\AttributeTok{method =} \StringTok{"loess"}\NormalTok{, }\AttributeTok{span =} \FloatTok{0.25}\NormalTok{, }\AttributeTok{linewidth =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ Gender\_label, }\AttributeTok{ncol =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{xintercept =} \DecValTok{1990}\NormalTok{, }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{, }\AttributeTok{colour =} \StringTok{"grey40"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{annotate}\NormalTok{(}\StringTok{"text"}\NormalTok{, }\AttributeTok{x =} \DecValTok{1991}\NormalTok{, }\AttributeTok{y =} \FloatTok{0.55}\NormalTok{, }\AttributeTok{label =} \StringTok{"1990"}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{0}\NormalTok{,}
             \AttributeTok{size =} \FloatTok{3.2}\NormalTok{, }\AttributeTok{colour =} \StringTok{"grey40"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{scale\_colour\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"\#264653"}\NormalTok{, }\StringTok{"\#E9C46A"}\NormalTok{, }\StringTok{"\#E76F51"}\NormalTok{)) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Do Popular Baby Names Persist? Spearman Rank Correlation Over Time"}\NormalTok{,}
         \AttributeTok{subtitle =} \StringTok{"Top{-}25 names correlated with rankings 1{-}{-}3 years later"}\NormalTok{,}
         \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{y =} \FunctionTok{expression}\NormalTok{(Spearman}\SpecialCharTok{\textasciitilde{}}\NormalTok{rho), }\AttributeTok{colour =} \StringTok{"Lag"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{13}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"top"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Q2_Baby_Name_files/figure-latex/persistence-plot-1} \end{center}

\subsection{Pre- vs Post-1990}\label{pre--vs-post-1990}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{persistence\_df }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Era =} \FunctionTok{if\_else}\NormalTok{(Year }\SpecialCharTok{\textless{}} \DecValTok{1990}\NormalTok{, }\StringTok{"Pre{-}1990"}\NormalTok{, }\StringTok{"1990 onwards"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(Era, Gender, Lag) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{Mean\_rho   =} \FunctionTok{round}\NormalTok{(}\FunctionTok{mean}\NormalTok{(Correlation, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\DecValTok{3}\NormalTok{),}
              \AttributeTok{Median\_rho =} \FunctionTok{round}\NormalTok{(}\FunctionTok{median}\NormalTok{(Correlation, }\AttributeTok{na.rm =} \ConstantTok{TRUE}\NormalTok{), }\DecValTok{3}\NormalTok{),}
              \AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Gender =} \FunctionTok{if\_else}\NormalTok{(Gender }\SpecialCharTok{==} \StringTok{"F"}\NormalTok{, }\StringTok{"Girls"}\NormalTok{, }\StringTok{"Boys"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{arrange}\NormalTok{(Gender, Lag, Era) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{kable}\NormalTok{(}\AttributeTok{caption =} \StringTok{"Mean Spearman rho: Pre{-}1990 vs 1990 Onwards"}\NormalTok{,}
          \AttributeTok{booktabs =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{latex\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold\_position"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{column\_spec}\NormalTok{(}\DecValTok{4}\NormalTok{, }\AttributeTok{bold =} \ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{llr>{}rr}
\caption{\label{tab:persistence-table}Mean Spearman rho: Pre-1990 vs 1990 Onwards}\\
\toprule
Era & Gender & Lag & Mean\_rho & Median\_rho\\
\midrule
\cellcolor{gray!10}{1990 onwards} & \cellcolor{gray!10}{Boys} & \cellcolor{gray!10}{1} & \textbf{\cellcolor{gray!10}{0.950}} & \cellcolor{gray!10}{0.952}\\
Pre-1990 & Boys & 1 & \textbf{0.981} & 0.987\\
\cellcolor{gray!10}{1990 onwards} & \cellcolor{gray!10}{Boys} & \cellcolor{gray!10}{2} & \textbf{\cellcolor{gray!10}{0.891}} & \cellcolor{gray!10}{0.905}\\
Pre-1990 & Boys & 2 & \textbf{0.958} & 0.968\\
\cellcolor{gray!10}{1990 onwards} & \cellcolor{gray!10}{Boys} & \cellcolor{gray!10}{3} & \textbf{\cellcolor{gray!10}{0.836}} & \cellcolor{gray!10}{0.852}\\
\addlinespace
Pre-1990 & Boys & 3 & \textbf{0.934} & 0.950\\
\cellcolor{gray!10}{1990 onwards} & \cellcolor{gray!10}{Girls} & \cellcolor{gray!10}{1} & \textbf{\cellcolor{gray!10}{0.937}} & \cellcolor{gray!10}{0.940}\\
Pre-1990 & Girls & 1 & \textbf{0.952} & 0.960\\
\cellcolor{gray!10}{1990 onwards} & \cellcolor{gray!10}{Girls} & \cellcolor{gray!10}{2} & \textbf{\cellcolor{gray!10}{0.868}} & \cellcolor{gray!10}{0.870}\\
Pre-1990 & Girls & 2 & \textbf{0.900} & 0.914\\
\addlinespace
\cellcolor{gray!10}{1990 onwards} & \cellcolor{gray!10}{Girls} & \cellcolor{gray!10}{3} & \textbf{\cellcolor{gray!10}{0.815}} & \cellcolor{gray!10}{0.809}\\
Pre-1990 & Girls & 3 & \textbf{0.853} & 0.867\\
\bottomrule
\end{longtable}

\textbf{Key findings:}

\begin{itemize}
\tightlist
\item
  \textbf{Confirmed:} Post-1990 naming trends show \textbf{lower
  persistence} --- popular names churn faster for both genders.
\item
  The decline is most visible at longer lags: the 3-year lag \(\rho\)
  dropped from \$\sim\$0.93 (boys) and \$\sim\$0.85 (girls) pre-1990 to
  \$\sim\$0.84 and \$\sim\$0.82 post-1990.
\item
  Boys' persistence dropped \textbf{more sharply} than girls', narrowing
  the historical gender gap --- both genders are now converging toward
  faster naming churn.
\item
  This supports the agency's hypothesis: since the 1990s, popular name
  trends have been slower to persist than in earlier decades.
\end{itemize}

\newpage

\section{Year-on-Year Surges}\label{year-on-year-surges}

\subsection{Top Surges Table}\label{top-surges-table}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{yoy }\OtherTok{\textless{}{-}} \FunctionTok{compute\_yoy\_change}\NormalTok{(national, }\AttributeTok{min\_prev =} \DecValTok{50}\NormalTok{)}

\NormalTok{top\_surges }\OtherTok{\textless{}{-}}\NormalTok{ yoy }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(Pct)) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{slice\_head}\NormalTok{(}\AttributeTok{n =} \DecValTok{30}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{top\_surges }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(Name, Gender, Year, Prev, Total, Change, Pct) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Gender =} \FunctionTok{if\_else}\NormalTok{(Gender }\SpecialCharTok{==} \StringTok{"F"}\NormalTok{, }\StringTok{"Girl"}\NormalTok{, }\StringTok{"Boy"}\NormalTok{),}
           \AttributeTok{Pct =} \FunctionTok{paste0}\NormalTok{(}\StringTok{"+"}\NormalTok{, }\FunctionTok{round}\NormalTok{(Pct, }\DecValTok{0}\NormalTok{), }\StringTok{"\%"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{slice\_head}\NormalTok{(}\AttributeTok{n =} \DecValTok{15}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{kable}\NormalTok{(}\AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Name"}\NormalTok{, }\StringTok{"Gender"}\NormalTok{, }\StringTok{"Year"}\NormalTok{, }\StringTok{"Prev Year"}\NormalTok{, }\StringTok{"Surge Year"}\NormalTok{,}
                         \StringTok{"Change"}\NormalTok{, }\StringTok{"Pct Change"}\NormalTok{),}
          \AttributeTok{caption =} \StringTok{"Top 15 Biggest Year{-}on{-}Year Name Surges"}\NormalTok{,}
          \AttributeTok{booktabs =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{latex\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold\_position"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{llrrrrl}
\caption{\label{tab:surges-table}Top 15 Biggest Year-on-Year Name Surges}\\
\toprule
Name & Gender & Year & Prev Year & Surge Year & Change & Pct Change\\
\midrule
\cellcolor{gray!10}{Marquita} & \cellcolor{gray!10}{Girl} & \cellcolor{gray!10}{1983} & \cellcolor{gray!10}{96} & \cellcolor{gray!10}{2522} & \cellcolor{gray!10}{2426} & \cellcolor{gray!10}{+2527\%}\\
Woodrow & Boy & 1912 & 82 & 1826 & 1744 & +2127\%\\
\cellcolor{gray!10}{Nevaeh} & \cellcolor{gray!10}{Girl} & \cellcolor{gray!10}{2001} & \cellcolor{gray!10}{53} & \cellcolor{gray!10}{1179} & \cellcolor{gray!10}{1126} & \cellcolor{gray!10}{+2125\%}\\
Tammy & Girl & 1957 & 204 & 4363 & 4159 & +2039\%\\
\cellcolor{gray!10}{Devante} & \cellcolor{gray!10}{Boy} & \cellcolor{gray!10}{1992} & \cellcolor{gray!10}{86} & \cellcolor{gray!10}{1551} & \cellcolor{gray!10}{1465} & \cellcolor{gray!10}{+1703\%}\\
\addlinespace
Kiara & Girl & 1989 & 171 & 2595 & 2424 & +1418\%\\
\cellcolor{gray!10}{Jayceon} & \cellcolor{gray!10}{Boy} & \cellcolor{gray!10}{2013} & \cellcolor{gray!10}{128} & \cellcolor{gray!10}{1827} & \cellcolor{gray!10}{1699} & \cellcolor{gray!10}{+1327\%}\\
Tennille & Girl & 1976 & 53 & 736 & 683 & +1289\%\\
\cellcolor{gray!10}{Dawson} & \cellcolor{gray!10}{Boy} & \cellcolor{gray!10}{1998} & \cellcolor{gray!10}{141} & \cellcolor{gray!10}{1883} & \cellcolor{gray!10}{1742} & \cellcolor{gray!10}{+1235\%}\\
Desiree & Girl & 1955 & 55 & 723 & 668 & +1215\%\\
\addlinespace
\cellcolor{gray!10}{Brianne} & \cellcolor{gray!10}{Girl} & \cellcolor{gray!10}{1979} & \cellcolor{gray!10}{133} & \cellcolor{gray!10}{1655} & \cellcolor{gray!10}{1522} & \cellcolor{gray!10}{+1144\%}\\
Ashanti & Girl & 2002 & 253 & 2927 & 2674 & +1057\%\\
\cellcolor{gray!10}{Ashton} & \cellcolor{gray!10}{Girl} & \cellcolor{gray!10}{1986} & \cellcolor{gray!10}{83} & \cellcolor{gray!10}{916} & \cellcolor{gray!10}{833} & \cellcolor{gray!10}{+1004\%}\\
Sabrina & Girl & 1955 & 103 & 1091 & 988 & +959\%\\
\cellcolor{gray!10}{Amaya} & \cellcolor{gray!10}{Girl} & \cellcolor{gray!10}{1999} & \cellcolor{gray!10}{63} & \cellcolor{gray!10}{656} & \cellcolor{gray!10}{593} & \cellcolor{gray!10}{+941\%}\\
\bottomrule
\end{longtable}

\textbf{Notable entries:}

\begin{itemize}
\tightlist
\item
  \textbf{Nevaeh} (+2,125\% in 2001) is ``heaven'' spelled backwards ---
  a name essentially invented by musician Sonny Sandoval when he
  appeared on MTV and mentioned naming his daughter Nevaeh. It went from
  53 births to over 1,000 in a single year.
\item
  \textbf{Woodrow} (+2,127\% in 1912) coincides precisely with Woodrow
  Wilson's presidential campaign, confirming that political naming
  influence is not a modern phenomenon.
\item
  \textbf{Tammy} (+2,039\% in 1957) surged alongside the hit film
  \emph{Tammy and the Bachelor} starring Debbie Reynolds, whose theme
  song topped the Billboard charts.
\end{itemize}

\subsection{Cultural Spike Case
Studies}\label{cultural-spike-case-studies}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cultural\_trends }\OtherTok{\textless{}{-}} \FunctionTok{build\_cultural\_trends}\NormalTok{(national)}

\NormalTok{cultural\_trends }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Year, }\AttributeTok{y =}\NormalTok{ Total)) }\SpecialCharTok{+}
    \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{colour =} \StringTok{"\#2A9D8F"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{0.8}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{geom\_vline}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{xintercept =}\NormalTok{ Event\_Year), }\AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{,}
               \AttributeTok{colour =} \StringTok{"\#E76F51"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{0.6}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}} \FunctionTok{glue}\NormalTok{(}\StringTok{"\{Name\} (\{Event\})"}\NormalTok{), }\AttributeTok{scales =} \StringTok{"free\_y"}\NormalTok{, }\AttributeTok{ncol =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Cultural Events Drive Baby Name Surges"}\NormalTok{,}
         \AttributeTok{subtitle =} \StringTok{"Dashed red line = cultural event year"}\NormalTok{,}
         \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{y =} \StringTok{"Births / Year"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{11}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{strip.text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{face =} \StringTok{"bold"}\NormalTok{, }\AttributeTok{size =} \DecValTok{9}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Q2_Baby_Name_files/figure-latex/cultural-spikes-1} \end{center}

\textbf{Key findings:}

\begin{itemize}
\tightlist
\item
  \textbf{Katina} spikes in 1974 (TV character on \emph{Where the Heart
  Is}).
\item
  \textbf{Whitney} surged through the mid-1980s with Whitney Houston's
  career.
\item
  \textbf{Ariel} jumped after \emph{The Little Mermaid} (1989);
  \textbf{Miley} didn't exist before \emph{Hannah Montana} (2006).
\item
  \textbf{Daenerys} / \textbf{Khaleesi} are entirely new names created
  by \emph{Game of Thrones}.
\end{itemize}

\newpage

\section{Billboard Music Influence}\label{billboard-music-influence}

\subsection{Artist--Baby Overlay}\label{artistbaby-overlay}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{billboard\_names   }\OtherTok{\textless{}{-}} \FunctionTok{parse\_billboard\_artists}\NormalTok{(Top\_100\_Billboard)}
\NormalTok{billboard\_summary }\OtherTok{\textless{}{-}} \FunctionTok{summarise\_billboard}\NormalTok{(billboard\_names)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{music\_names   }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Whitney"}\NormalTok{, }\StringTok{"Adele"}\NormalTok{, }\StringTok{"Rihanna"}\NormalTok{, }\StringTok{"Beyonce"}\NormalTok{, }\StringTok{"Elvis"}\NormalTok{, }\StringTok{"Madonna"}\NormalTok{)}
\NormalTok{music\_overlay }\OtherTok{\textless{}{-}} \FunctionTok{build\_music\_overlay}\NormalTok{(music\_names, national, billboard\_summary)}

\NormalTok{music\_overlay }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Year, }\AttributeTok{y =}\NormalTok{ Value, }\AttributeTok{colour =}\NormalTok{ Series)) }\SpecialCharTok{+}
    \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{linewidth =} \FloatTok{0.8}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ Name, }\AttributeTok{scales =} \StringTok{"free\_y"}\NormalTok{, }\AttributeTok{ncol =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{scale\_colour\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"Baby Name Count"} \OtherTok{=} \StringTok{"\#2A9D8F"}\NormalTok{,}
                                   \StringTok{"Billboard Weeks"}  \OtherTok{=} \StringTok{"\#E76F51"}\NormalTok{)) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Does Billboard Fame Drive Baby Names?"}\NormalTok{,}
         \AttributeTok{subtitle =} \StringTok{"Baby name popularity vs weeks on the Billboard Top 100"}\NormalTok{,}
         \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{y =} \StringTok{"Count / Weeks"}\NormalTok{, }\AttributeTok{colour =} \ConstantTok{NULL}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{11}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"top"}\NormalTok{, }\AttributeTok{strip.text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{face =} \StringTok{"bold"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Q2_Baby_Name_files/figure-latex/billboard-overlay-1} \end{center}

\subsection{Systematic Match Table}\label{systematic-match-table}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{top\_billboard }\OtherTok{\textless{}{-}}\NormalTok{ billboard\_summary }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{group\_by}\NormalTok{(Name) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summarise}\NormalTok{(}\AttributeTok{Total\_Weeks =} \FunctionTok{sum}\NormalTok{(weeks\_charting),}
              \AttributeTok{Peak\_Year   =}\NormalTok{ Year[}\FunctionTok{which.max}\NormalTok{(weeks\_charting)],}
              \AttributeTok{.groups =} \StringTok{"drop"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(Total\_Weeks }\SpecialCharTok{\textgreater{}=} \DecValTok{100}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(Total\_Weeks))}

\NormalTok{billboard\_baby\_match }\OtherTok{\textless{}{-}}\NormalTok{ top\_billboard }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{inner\_join}\NormalTok{(yoy }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(Pct }\SpecialCharTok{\textgreater{}} \DecValTok{20}\NormalTok{), }\AttributeTok{by =} \StringTok{"Name"}\NormalTok{,}
               \AttributeTok{suffix =} \FunctionTok{c}\NormalTok{(}\StringTok{"\_chart"}\NormalTok{, }\StringTok{"\_baby"}\NormalTok{), }\AttributeTok{relationship =} \StringTok{"many{-}to{-}many"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(}\FunctionTok{abs}\NormalTok{(Peak\_Year }\SpecialCharTok{{-}}\NormalTok{ Year) }\SpecialCharTok{\textless{}=} \DecValTok{3}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{arrange}\NormalTok{(}\FunctionTok{desc}\NormalTok{(Pct)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{distinct}\NormalTok{(Name, }\AttributeTok{.keep\_all =} \ConstantTok{TRUE}\NormalTok{)}

\NormalTok{billboard\_baby\_match }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(Name, Gender, Peak\_Year, Year, Total\_Weeks, Prev, Total, Pct) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Pct =} \FunctionTok{paste0}\NormalTok{(}\StringTok{"+"}\NormalTok{, }\FunctionTok{round}\NormalTok{(Pct, }\DecValTok{0}\NormalTok{), }\StringTok{"\%"}\NormalTok{),}
           \AttributeTok{Gender =} \FunctionTok{if\_else}\NormalTok{(Gender }\SpecialCharTok{==} \StringTok{"F"}\NormalTok{, }\StringTok{"Girl"}\NormalTok{, }\StringTok{"Boy"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{slice\_head}\NormalTok{(}\AttributeTok{n =} \DecValTok{12}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{kable}\NormalTok{(}\AttributeTok{col.names =} \FunctionTok{c}\NormalTok{(}\StringTok{"Name"}\NormalTok{, }\StringTok{"Gender"}\NormalTok{, }\StringTok{"Chart Peak"}\NormalTok{, }\StringTok{"Name Surge Year"}\NormalTok{,}
                         \StringTok{"Billboard Weeks"}\NormalTok{, }\StringTok{"Prev Births"}\NormalTok{, }\StringTok{"Surge Births"}\NormalTok{, }\StringTok{"Pct Change"}\NormalTok{),}
          \AttributeTok{caption =} \StringTok{"Billboard Artists Whose Fame Coincides with Baby Name Surges"}\NormalTok{,}
          \AttributeTok{booktabs =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{kable\_styling}\NormalTok{(}\AttributeTok{latex\_options =} \FunctionTok{c}\NormalTok{(}\StringTok{"striped"}\NormalTok{, }\StringTok{"hold\_position"}\NormalTok{), }\AttributeTok{full\_width =} \ConstantTok{FALSE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[t]{llrrrrrl}
\caption{\label{tab:billboard-match}Billboard Artists Whose Fame Coincides with Baby Name Surges}\\
\toprule
Name & Gender & Chart Peak & Name Surge Year & Billboard Weeks & Prev Births & Surge Births & Pct Change\\
\midrule
\cellcolor{gray!10}{Tennille} & \cellcolor{gray!10}{Girl} & \cellcolor{gray!10}{1976} & \cellcolor{gray!10}{1976} & \cellcolor{gray!10}{198} & \cellcolor{gray!10}{53} & \cellcolor{gray!10}{736} & \cellcolor{gray!10}{+1289\%}\\
Ashanti & Girl & 2002 & 2002 & 289 & 253 & 2927 & +1057\%\\
\cellcolor{gray!10}{Mya} & \cellcolor{gray!10}{Girl} & \cellcolor{gray!10}{2000} & \cellcolor{gray!10}{1998} & \cellcolor{gray!10}{181} & \cellcolor{gray!10}{136} & \cellcolor{gray!10}{1251} & \cellcolor{gray!10}{+820\%}\\
Miley & Girl & 2009 & 2007 & 348 & 141 & 1213 & +760\%\\
\cellcolor{gray!10}{Shanice} & \cellcolor{gray!10}{Girl} & \cellcolor{gray!10}{1992} & \cellcolor{gray!10}{1992} & \cellcolor{gray!10}{106} & \cellcolor{gray!10}{259} & \cellcolor{gray!10}{1837} & \cellcolor{gray!10}{+609\%}\\
\addlinespace
Sheena & Girl & 1981 & 1981 & 290 & 101 & 628 & +522\%\\
\cellcolor{gray!10}{Sade} & \cellcolor{gray!10}{Girl} & \cellcolor{gray!10}{1985} & \cellcolor{gray!10}{1986} & \cellcolor{gray!10}{140} & \cellcolor{gray!10}{355} & \cellcolor{gray!10}{1214} & \cellcolor{gray!10}{+242\%}\\
Brantley & Boy & 2014 & 2011 & 164 & 284 & 951 & +235\%\\
\cellcolor{gray!10}{Shania} & \cellcolor{gray!10}{Girl} & \cellcolor{gray!10}{1999} & \cellcolor{gray!10}{1996} & \cellcolor{gray!10}{298} & \cellcolor{gray!10}{546} & \cellcolor{gray!10}{1827} & \cellcolor{gray!10}{+235\%}\\
Emerson & Girl & 2002 & 2005 & 112 & 221 & 659 & +198\%\\
\addlinespace
\cellcolor{gray!10}{Beyonce} & \cellcolor{gray!10}{Girl} & \cellcolor{gray!10}{2009} & \cellcolor{gray!10}{2007} & \cellcolor{gray!10}{884} & \cellcolor{gray!10}{56} & \cellcolor{gray!10}{145} & \cellcolor{gray!10}{+159\%}\\
Ciara & Girl & 2005 & 2005 & 339 & 954 & 2308 & +142\%\\
\bottomrule
\end{longtable}

\textbf{Key findings:}

\begin{itemize}
\tightlist
\item
  \textbf{Whitney} is the clearest example: Billboard dominance led to a
  massive baby name surge.
\item
  \textbf{Elvis} shows a mid-1950s spike timed with his breakthrough.
\item
  Effect is strongest for \textbf{solo female artists} with distinctive
  first names.
\end{itemize}

\newpage

\section{HBO and TV/Movie Influence}\label{hbo-and-tvmovie-influence}

\subsection{HBO Name Trends}\label{hbo-name-trends}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hbo\_names   }\OtherTok{\textless{}{-}} \FunctionTok{extract\_hbo\_names}\NormalTok{(HBO\_credits, HBO\_titles)}
\NormalTok{hbo\_popular }\OtherTok{\textless{}{-}} \FunctionTok{summarise\_hbo\_names}\NormalTok{(hbo\_names)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hbo\_spotlight     }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Carrie"}\NormalTok{, }\StringTok{"Arya"}\NormalTok{, }\StringTok{"Dorothy"}\NormalTok{, }\StringTok{"Tony"}\NormalTok{, }\StringTok{"Sophia"}\NormalTok{, }\StringTok{"Olivia"}\NormalTok{)}
\NormalTok{hbo\_baby\_overlay  }\OtherTok{\textless{}{-}} \FunctionTok{build\_hbo\_baby\_overlay}\NormalTok{(hbo\_spotlight, national, hbo\_names)}

\NormalTok{hbo\_baby\_overlay }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Year, }\AttributeTok{y =}\NormalTok{ Total)) }\SpecialCharTok{+}
    \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{colour =} \StringTok{"\#264653"}\NormalTok{, }\AttributeTok{linewidth =} \FloatTok{0.8}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ Name, }\AttributeTok{scales =} \StringTok{"free\_y"}\NormalTok{, }\AttributeTok{ncol =} \DecValTok{2}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"HBO Character / Actor Names and Baby Name Trajectories"}\NormalTok{,}
         \AttributeTok{subtitle =} \StringTok{"Exploring whether popular TV characters influence naming"}\NormalTok{,}
         \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{y =} \StringTok{"Births / Year"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{11}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{strip.text =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{face =} \StringTok{"bold"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Q2_Baby_Name_files/figure-latex/hbo-plot-1} \end{center}

\textbf{Key findings:}

\begin{itemize}
\tightlist
\item
  \textbf{Arya} was nearly non-existent before \emph{Game of Thrones}
  (2011) --- textbook cultural naming.
\item
  \textbf{Tony} (The Sopranos) had an established baseline --- cultural
  reinforcement rather than creation.
\item
  \textbf{Sophia} and \textbf{Olivia} rose independently of any single
  show.
\end{itemize}

\newpage

\section{Decade Bubble Visualisation}\label{decade-bubble-visualisation}

\subsection{Boys}\label{boys}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{boys\_bubble }\OtherTok{\textless{}{-}} \FunctionTok{top\_names\_by\_decade}\NormalTok{(national, }\StringTok{"M"}\NormalTok{, }\AttributeTok{n =} \DecValTok{10}\NormalTok{)}

\NormalTok{cultural\_boy\_names }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Elvis"}\NormalTok{, }\StringTok{"Barack"}\NormalTok{, }\StringTok{"Jayden"}\NormalTok{, }\StringTok{"Muhammad"}\NormalTok{, }\StringTok{"Kanye"}\NormalTok{)}

\NormalTok{boys\_bubble }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Cultural =} \FunctionTok{if\_else}\NormalTok{(Name }\SpecialCharTok{\%in\%}\NormalTok{ cultural\_boy\_names, }\StringTok{"Cultural link"}\NormalTok{, }\StringTok{"Standard"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(Name, }\SpecialCharTok{{-}}\NormalTok{Total), }\AttributeTok{y =}\NormalTok{ Decade, }\AttributeTok{size =}\NormalTok{ Total, }\AttributeTok{colour =}\NormalTok{ Cultural)) }\SpecialCharTok{+}
    \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{scale\_size\_continuous}\NormalTok{(}\AttributeTok{range =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{15}\NormalTok{), }\AttributeTok{labels =}\NormalTok{ comma) }\SpecialCharTok{+}
    \FunctionTok{scale\_colour\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"Cultural link"} \OtherTok{=} \StringTok{"\#E76F51"}\NormalTok{, }\StringTok{"Standard"} \OtherTok{=} \StringTok{"\#2A9D8F"}\NormalTok{)) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Most Popular Boys\textquotesingle{} Names by Decade"}\NormalTok{,}
         \AttributeTok{subtitle =} \StringTok{"Bubble size = total births; orange = culturally{-}driven name"}\NormalTok{,}
         \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{y =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{size =} \StringTok{"Total Births"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{11}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{, }\AttributeTok{size =} \DecValTok{8}\NormalTok{),}
          \AttributeTok{legend.position =} \StringTok{"right"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Q2_Baby_Name_files/figure-latex/bubble-boys-1} \end{center}

\subsection{Girls}\label{girls}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{girls\_bubble }\OtherTok{\textless{}{-}} \FunctionTok{top\_names\_by\_decade}\NormalTok{(national, }\StringTok{"F"}\NormalTok{, }\AttributeTok{n =} \DecValTok{10}\NormalTok{)}

\NormalTok{cultural\_girl\_names }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"Whitney"}\NormalTok{, }\StringTok{"Ariel"}\NormalTok{, }\StringTok{"Miley"}\NormalTok{, }\StringTok{"Aaliyah"}\NormalTok{,}
                          \StringTok{"Khaleesi"}\NormalTok{, }\StringTok{"Daenerys"}\NormalTok{, }\StringTok{"Madonna"}\NormalTok{, }\StringTok{"Arya"}\NormalTok{)}

\NormalTok{girls\_bubble }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Cultural =} \FunctionTok{if\_else}\NormalTok{(Name }\SpecialCharTok{\%in\%}\NormalTok{ cultural\_girl\_names, }\StringTok{"Cultural link"}\NormalTok{, }\StringTok{"Standard"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \FunctionTok{reorder}\NormalTok{(Name, }\SpecialCharTok{{-}}\NormalTok{Total), }\AttributeTok{y =}\NormalTok{ Decade, }\AttributeTok{size =}\NormalTok{ Total, }\AttributeTok{colour =}\NormalTok{ Cultural)) }\SpecialCharTok{+}
    \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{scale\_size\_continuous}\NormalTok{(}\AttributeTok{range =} \FunctionTok{c}\NormalTok{(}\DecValTok{2}\NormalTok{, }\DecValTok{15}\NormalTok{), }\AttributeTok{labels =}\NormalTok{ comma) }\SpecialCharTok{+}
    \FunctionTok{scale\_colour\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"Cultural link"} \OtherTok{=} \StringTok{"\#E76F51"}\NormalTok{, }\StringTok{"Standard"} \OtherTok{=} \StringTok{"\#264653"}\NormalTok{)) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Most Popular Girls\textquotesingle{} Names by Decade"}\NormalTok{,}
         \AttributeTok{subtitle =} \StringTok{"Bubble size = total births; orange = culturally{-}driven name"}\NormalTok{,}
         \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{y =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{size =} \StringTok{"Total Births"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{11}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{axis.text.x =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{angle =} \DecValTok{45}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{1}\NormalTok{, }\AttributeTok{size =} \DecValTok{8}\NormalTok{),}
          \AttributeTok{legend.position =} \StringTok{"right"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Q2_Baby_Name_files/figure-latex/bubble-girls-1} \end{center}

\newpage

\section{Name Diversity Over Time}\label{name-diversity-over-time}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{diversity\_df }\OtherTok{\textless{}{-}} \FunctionTok{build\_diversity\_df}\NormalTok{(national)}

\NormalTok{diversity\_df }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Gender =} \FunctionTok{if\_else}\NormalTok{(Gender }\SpecialCharTok{==} \StringTok{"F"}\NormalTok{, }\StringTok{"Girls"}\NormalTok{, }\StringTok{"Boys"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Year, }\AttributeTok{y =}\NormalTok{ Names\_for\_50pct, }\AttributeTok{colour =}\NormalTok{ Gender)) }\SpecialCharTok{+}
    \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{linewidth =} \FloatTok{0.9}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{scale\_colour\_manual}\NormalTok{(}\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"Girls"} \OtherTok{=} \StringTok{"\#E76F51"}\NormalTok{, }\StringTok{"Boys"} \OtherTok{=} \StringTok{"\#2A9D8F"}\NormalTok{)) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Naming Diversity Is Exploding"}\NormalTok{,}
         \AttributeTok{subtitle =} \StringTok{"Number of unique names needed to cover 50\% of all births"}\NormalTok{,}
         \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{y =} \StringTok{"Names for 50\% Coverage"}\NormalTok{, }\AttributeTok{colour =} \ConstantTok{NULL}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{13}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position =} \StringTok{"top"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Q2_Baby_Name_files/figure-latex/diversity-plot-1} \end{center}

\textbf{Key findings:}

\begin{itemize}
\tightlist
\item
  In 1910, fewer than \textbf{10 names} covered half of all births per
  gender.
\item
  By 2014, it takes \textbf{50+} (boys) and \textbf{100+} (girls) names
  to reach the same threshold.
\item
  Confirms the persistence analysis: modern parents are far more
  creative.
\end{itemize}

\newpage

\section{All-Time Top Names}\label{all-time-top-names}

\subsection{Girls}\label{girls-1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{national }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(Name }\SpecialCharTok{\%in\%} \FunctionTok{get\_alltime\_top}\NormalTok{(national, }\StringTok{"F"}\NormalTok{), Gender }\SpecialCharTok{==} \StringTok{"F"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Year, }\AttributeTok{y =}\NormalTok{ Total, }\AttributeTok{colour =}\NormalTok{ Name)) }\SpecialCharTok{+}
    \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{linewidth =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ comma) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"All{-}Time Top 10 Girls\textquotesingle{} Names: Trajectories"}\NormalTok{,}
         \AttributeTok{subtitle =} \StringTok{"Each name shows a clear rise{-}and{-}fall lifecycle"}\NormalTok{,}
         \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{y =} \StringTok{"Births / Year"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{12}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Q2_Baby_Name_files/figure-latex/top10-girls-1} \end{center}

\subsection{Boys}\label{boys-1}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{national }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(Name }\SpecialCharTok{\%in\%} \FunctionTok{get\_alltime\_top}\NormalTok{(national, }\StringTok{"M"}\NormalTok{), Gender }\SpecialCharTok{==} \StringTok{"M"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{ggplot}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ Year, }\AttributeTok{y =}\NormalTok{ Total, }\AttributeTok{colour =}\NormalTok{ Name)) }\SpecialCharTok{+}
    \FunctionTok{geom\_line}\NormalTok{(}\AttributeTok{linewidth =} \FloatTok{0.7}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{scale\_y\_continuous}\NormalTok{(}\AttributeTok{labels =}\NormalTok{ comma) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"All{-}Time Top 10 Boys\textquotesingle{} Names: Trajectories"}\NormalTok{,}
         \AttributeTok{subtitle =} \StringTok{"Classic boys\textquotesingle{} names persist far longer than girls\textquotesingle{}"}\NormalTok{,}
         \AttributeTok{x =} \ConstantTok{NULL}\NormalTok{, }\AttributeTok{y =} \StringTok{"Births / Year"}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{12}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{center}\includegraphics{Q2_Baby_Name_files/figure-latex/top10-boys-1} \end{center}

\newpage

\section{Summary and Recommendations}\label{summary-and-recommendations}

\begin{longtabu} to \linewidth {>{\raggedright\arraybackslash}p{7cm}>{\raggedright}X}
\caption{\label{tab:summary-table}Summary of Key Findings for the Toy Agency}\\
\toprule
Finding & Evidence\\
\midrule
\textbf{\cellcolor{gray!10}{Post-1990 names are less persistent}} & \cellcolor{gray!10}{Spearman rho drops for 1--3 year lags after 1990}\\
\textbf{Girls' names churn faster than boys'} & Lower persistence rho and faster diversity growth for girls\\
\textbf{\cellcolor{gray!10}{Naming diversity has exploded}} & \cellcolor{gray!10}{50\textbackslash{}\%-coverage threshold grew from \textasciitilde{}10 to 100+ names}\\
\textbf{TV shows create instant name spikes} & Katina (1974), Arya/Khaleesi (2011+), Miley (2006)\\
\textbf{\cellcolor{gray!10}{Music icons drive sustained naming trends}} & \cellcolor{gray!10}{Whitney (1985--92), Elvis (1950s), Aaliyah (1990s)}\\
\addlinespace
\textbf{Political figures can spike baby names} & Barack surged during the 2008 campaign\\
\textbf{\cellcolor{gray!10}{Cultural names are individually smaller but collectively impactful}} & \cellcolor{gray!10}{Each fad peaks lower but total variety is much higher}\\
\bottomrule
\end{longtabu}

\textbf{Recommendations for the toy agency:}

\begin{itemize}
\tightlist
\item
  \textbf{Monitor Billboard and streaming charts} --- artist first names
  influence baby naming within 1--3 years of peak fame.
\item
  \textbf{Track new TV/streaming character names} --- unique fantasy
  names can emerge from zero to thousands within 2--3 years.
\item
  \textbf{Do not bet on longevity} --- modern name trends last roughly
  5--10 years at most; refresh toy character names every product cycle.
\item
  \textbf{Classic names still have a floor} --- James, William, Sophia,
  and Olivia remain safe bets for broad-market appeal.
\end{itemize}

\end{document}
